# Generated by Django 2.2.16 on 2020-11-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file_path', models.FilePathField(match='.*\\.csv', path='/home/aschlapsi/Projects/swchars/swexplorer/files')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
